/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedProjectsProjectIdRouteImport } from './routes/_protected/projects/$projectId'
import { Route as ProtectedProjectsProjectIdIndexRouteImport } from './routes/_protected/projects/$projectId/index'
import { Route as ProtectedProjectsProjectIdVitalsRouteImport } from './routes/_protected/projects/$projectId/vitals'
import { Route as ProtectedProjectsProjectIdSystemHealthRouteImport } from './routes/_protected/projects/$projectId/system-health'
import { Route as ProtectedProjectsProjectIdSettingsRouteImport } from './routes/_protected/projects/$projectId/settings'
import { Route as ProtectedProjectsProjectIdRouteHealthRouteImport } from './routes/_protected/projects/$projectId/route-health'
import { Route as ProtectedProjectsProjectIdPerformanceRouteImport } from './routes/_protected/projects/$projectId/performance'
import { Route as ProtectedProjectsProjectIdOverviewRouteImport } from './routes/_protected/projects/$projectId/overview'
import { Route as ProtectedProjectsProjectIdNetworkRouteImport } from './routes/_protected/projects/$projectId/network'
import { Route as ProtectedProjectsProjectIdIssuesRouteImport } from './routes/_protected/projects/$projectId/issues'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedProjectsProjectIdRoute =
  ProtectedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProjectsProjectIdIndexRoute =
  ProtectedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)
const ProtectedProjectsProjectIdVitalsRoute =
  ProtectedProjectsProjectIdVitalsRouteImport.update({
    id: '/vitals',
    path: '/vitals',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)
const ProtectedProjectsProjectIdSystemHealthRoute =
  ProtectedProjectsProjectIdSystemHealthRouteImport.update({
    id: '/system-health',
    path: '/system-health',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)
const ProtectedProjectsProjectIdSettingsRoute =
  ProtectedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)
const ProtectedProjectsProjectIdRouteHealthRoute =
  ProtectedProjectsProjectIdRouteHealthRouteImport.update({
    id: '/route-health',
    path: '/route-health',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)
const ProtectedProjectsProjectIdPerformanceRoute =
  ProtectedProjectsProjectIdPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)
const ProtectedProjectsProjectIdOverviewRoute =
  ProtectedProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)
const ProtectedProjectsProjectIdNetworkRoute =
  ProtectedProjectsProjectIdNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)
const ProtectedProjectsProjectIdIssuesRoute =
  ProtectedProjectsProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdRouteWithChildren
  '/projects/$projectId/issues': typeof ProtectedProjectsProjectIdIssuesRoute
  '/projects/$projectId/network': typeof ProtectedProjectsProjectIdNetworkRoute
  '/projects/$projectId/overview': typeof ProtectedProjectsProjectIdOverviewRoute
  '/projects/$projectId/performance': typeof ProtectedProjectsProjectIdPerformanceRoute
  '/projects/$projectId/route-health': typeof ProtectedProjectsProjectIdRouteHealthRoute
  '/projects/$projectId/settings': typeof ProtectedProjectsProjectIdSettingsRoute
  '/projects/$projectId/system-health': typeof ProtectedProjectsProjectIdSystemHealthRoute
  '/projects/$projectId/vitals': typeof ProtectedProjectsProjectIdVitalsRoute
  '/projects/$projectId/': typeof ProtectedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/projects/$projectId/issues': typeof ProtectedProjectsProjectIdIssuesRoute
  '/projects/$projectId/network': typeof ProtectedProjectsProjectIdNetworkRoute
  '/projects/$projectId/overview': typeof ProtectedProjectsProjectIdOverviewRoute
  '/projects/$projectId/performance': typeof ProtectedProjectsProjectIdPerformanceRoute
  '/projects/$projectId/route-health': typeof ProtectedProjectsProjectIdRouteHealthRoute
  '/projects/$projectId/settings': typeof ProtectedProjectsProjectIdSettingsRoute
  '/projects/$projectId/system-health': typeof ProtectedProjectsProjectIdSystemHealthRoute
  '/projects/$projectId/vitals': typeof ProtectedProjectsProjectIdVitalsRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/projects/$projectId': typeof ProtectedProjectsProjectIdRouteWithChildren
  '/_protected/projects/$projectId/issues': typeof ProtectedProjectsProjectIdIssuesRoute
  '/_protected/projects/$projectId/network': typeof ProtectedProjectsProjectIdNetworkRoute
  '/_protected/projects/$projectId/overview': typeof ProtectedProjectsProjectIdOverviewRoute
  '/_protected/projects/$projectId/performance': typeof ProtectedProjectsProjectIdPerformanceRoute
  '/_protected/projects/$projectId/route-health': typeof ProtectedProjectsProjectIdRouteHealthRoute
  '/_protected/projects/$projectId/settings': typeof ProtectedProjectsProjectIdSettingsRoute
  '/_protected/projects/$projectId/system-health': typeof ProtectedProjectsProjectIdSystemHealthRoute
  '/_protected/projects/$projectId/vitals': typeof ProtectedProjectsProjectIdVitalsRoute
  '/_protected/projects/$projectId/': typeof ProtectedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/setup'
    | '/demo/i18n'
    | '/projects/$projectId'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/network'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/performance'
    | '/projects/$projectId/route-health'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/system-health'
    | '/projects/$projectId/vitals'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/setup'
    | '/demo/i18n'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/network'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/performance'
    | '/projects/$projectId/route-health'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/system-health'
    | '/projects/$projectId/vitals'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/about'
    | '/_auth/login'
    | '/_auth/setup'
    | '/demo/i18n'
    | '/_protected/'
    | '/_protected/projects/$projectId'
    | '/_protected/projects/$projectId/issues'
    | '/_protected/projects/$projectId/network'
    | '/_protected/projects/$projectId/overview'
    | '/_protected/projects/$projectId/performance'
    | '/_protected/projects/$projectId/route-health'
    | '/_protected/projects/$projectId/settings'
    | '/_protected/projects/$projectId/system-health'
    | '/_protected/projects/$projectId/vitals'
    | '/_protected/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemoI18nRoute: typeof DemoI18nRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/projects/$projectId': {
      id: '/_protected/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProtectedProjectsProjectIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/projects/$projectId/': {
      id: '/_protected/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProtectedProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProtectedProjectsProjectIdRoute
    }
    '/_protected/projects/$projectId/vitals': {
      id: '/_protected/projects/$projectId/vitals'
      path: '/vitals'
      fullPath: '/projects/$projectId/vitals'
      preLoaderRoute: typeof ProtectedProjectsProjectIdVitalsRouteImport
      parentRoute: typeof ProtectedProjectsProjectIdRoute
    }
    '/_protected/projects/$projectId/system-health': {
      id: '/_protected/projects/$projectId/system-health'
      path: '/system-health'
      fullPath: '/projects/$projectId/system-health'
      preLoaderRoute: typeof ProtectedProjectsProjectIdSystemHealthRouteImport
      parentRoute: typeof ProtectedProjectsProjectIdRoute
    }
    '/_protected/projects/$projectId/settings': {
      id: '/_protected/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProtectedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProtectedProjectsProjectIdRoute
    }
    '/_protected/projects/$projectId/route-health': {
      id: '/_protected/projects/$projectId/route-health'
      path: '/route-health'
      fullPath: '/projects/$projectId/route-health'
      preLoaderRoute: typeof ProtectedProjectsProjectIdRouteHealthRouteImport
      parentRoute: typeof ProtectedProjectsProjectIdRoute
    }
    '/_protected/projects/$projectId/performance': {
      id: '/_protected/projects/$projectId/performance'
      path: '/performance'
      fullPath: '/projects/$projectId/performance'
      preLoaderRoute: typeof ProtectedProjectsProjectIdPerformanceRouteImport
      parentRoute: typeof ProtectedProjectsProjectIdRoute
    }
    '/_protected/projects/$projectId/overview': {
      id: '/_protected/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof ProtectedProjectsProjectIdOverviewRouteImport
      parentRoute: typeof ProtectedProjectsProjectIdRoute
    }
    '/_protected/projects/$projectId/network': {
      id: '/_protected/projects/$projectId/network'
      path: '/network'
      fullPath: '/projects/$projectId/network'
      preLoaderRoute: typeof ProtectedProjectsProjectIdNetworkRouteImport
      parentRoute: typeof ProtectedProjectsProjectIdRoute
    }
    '/_protected/projects/$projectId/issues': {
      id: '/_protected/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof ProtectedProjectsProjectIdIssuesRouteImport
      parentRoute: typeof ProtectedProjectsProjectIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedProjectsProjectIdRouteChildren {
  ProtectedProjectsProjectIdIssuesRoute: typeof ProtectedProjectsProjectIdIssuesRoute
  ProtectedProjectsProjectIdNetworkRoute: typeof ProtectedProjectsProjectIdNetworkRoute
  ProtectedProjectsProjectIdOverviewRoute: typeof ProtectedProjectsProjectIdOverviewRoute
  ProtectedProjectsProjectIdPerformanceRoute: typeof ProtectedProjectsProjectIdPerformanceRoute
  ProtectedProjectsProjectIdRouteHealthRoute: typeof ProtectedProjectsProjectIdRouteHealthRoute
  ProtectedProjectsProjectIdSettingsRoute: typeof ProtectedProjectsProjectIdSettingsRoute
  ProtectedProjectsProjectIdSystemHealthRoute: typeof ProtectedProjectsProjectIdSystemHealthRoute
  ProtectedProjectsProjectIdVitalsRoute: typeof ProtectedProjectsProjectIdVitalsRoute
  ProtectedProjectsProjectIdIndexRoute: typeof ProtectedProjectsProjectIdIndexRoute
}

const ProtectedProjectsProjectIdRouteChildren: ProtectedProjectsProjectIdRouteChildren =
  {
    ProtectedProjectsProjectIdIssuesRoute:
      ProtectedProjectsProjectIdIssuesRoute,
    ProtectedProjectsProjectIdNetworkRoute:
      ProtectedProjectsProjectIdNetworkRoute,
    ProtectedProjectsProjectIdOverviewRoute:
      ProtectedProjectsProjectIdOverviewRoute,
    ProtectedProjectsProjectIdPerformanceRoute:
      ProtectedProjectsProjectIdPerformanceRoute,
    ProtectedProjectsProjectIdRouteHealthRoute:
      ProtectedProjectsProjectIdRouteHealthRoute,
    ProtectedProjectsProjectIdSettingsRoute:
      ProtectedProjectsProjectIdSettingsRoute,
    ProtectedProjectsProjectIdSystemHealthRoute:
      ProtectedProjectsProjectIdSystemHealthRoute,
    ProtectedProjectsProjectIdVitalsRoute:
      ProtectedProjectsProjectIdVitalsRoute,
    ProtectedProjectsProjectIdIndexRoute: ProtectedProjectsProjectIdIndexRoute,
  }

const ProtectedProjectsProjectIdRouteWithChildren =
  ProtectedProjectsProjectIdRoute._addFileChildren(
    ProtectedProjectsProjectIdRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedProjectsProjectIdRoute: typeof ProtectedProjectsProjectIdRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedProjectsProjectIdRoute: ProtectedProjectsProjectIdRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutRoute: AboutRoute,
  DemoI18nRoute: DemoI18nRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
